version: '3.9'
services:
  server:
    build:
      context: .
    ports:
      - "8000:3000"
    volumes:
      - ./app/src:/app/src
    command:
      sh -c "npm start"
    environment:
      DB_HOST:      postgres
      DB_NAME:      maxim_dev
      DB_USER:      maxim_dev
      DB_PASSWORD:  changeme
      DB_PORT:      5432